### PR TITLE
Read files with bigger buffer to speed up archive generation process

### PR DESCRIPTION
**Pull request by piRGoif**
Hello,
Thanks for this nice lib !

We're using it in our app to generate archives for backups. As there are some large files (especially the MySQL dump) we did this little modification that improves generation time a lot.

Instead of reading each files using a 512 bytes buffer, we're using a 1024*1024 byte buffer, until the last 512 bytes of the file.

### CODE REVIEW

**Comment by mrook** [comment]
Thanks, great idea!

I have a couple of questions/comments:

* Can you change the names of your intermediate variables to stay inline with the rest of the naming conventions in `Tar.php`?
* In terms of memory usage, maybe it would make sense to offer an option to fall back to the "original" buffer size. What do you think?

**Comment by piRGoif** [comment]
Thanks for your answer :)

I'm not sure to understand the naming convention... I see you're using underscores all lowercase. But some prefixes ($v_mtime, $p_header) also, and they don't seem to be visibility nor variable type dependant ?

We added those new variables, here are my proposition for new names, tell me what you think ?
$iLen : $length
$iBufferLen : $buffer_length
$iPack : $pack_size
$sPack  : $pack_format


Regarding adding an option, I can add a new parameter in the constructor with a default value, that will fix a protected attribute ?

**Comment by piRGoif** [comment]
Hello,
Can you confirm me you are ok with my previous propositions ? If yes I'll do a new commit immediately after O:)

**Comment by mrook** [comment]
👍

**Comment by piRGoif** [comment]
Hello,
I've pushed 2 commits yesterday, is this OK now ?

**Comment by piRGoif** [comment]
Thanks !
Are there any plans to publish a new release that would integrate this update ? O:)

**Comment by mrook** [comment]
Done!

**Comment by piRGoif** [comment]
Wonderful ! Many thanks !

**Pull request merged**
