### PR TITLE
Fix PHP 7.4 deprecation octdec()

### LINKED ISSUE #24: PHP 7.4 - Archive_Tar->_readHeader() throws deprecations
Testing PHP 7.4 with Drupal 8.8.x we get the following error:

```
PHPUnit 7.5.16 by Sebastian Bergmann and contributors.

Testing Drupal\Tests\config\Functional\ConfigImportUploadTest
E                                                                   1 / 1 (100%)

Time: 7.46 seconds, Memory: 4.00 MB

There was 1 error:

1) Drupal\Tests\config\Functional\ConfigImportUploadTest::testImport
Exception: Deprecated function: Invalid characters passed for attempted 
conversion, these have been ignored
Archive_Tar->_readHeader()() (Line: 1695)


/var/www/html/core/lib/Drupal/Core/Test/HttpClientMiddleware/TestHttpCl
ientMiddleware.php:51
/var/www/html/vendor/guzzlehttp/promises/src/Promise.php:203
/var/www/html/vendor/guzzlehttp/promises/src/Promise.php:156
/var/www/html/vendor/guzzlehttp/promises/src/TaskQueue.php:47
/var/www/html/vendor/guzzlehttp/promises/src/Promise.php:246
/var/www/html/vendor/guzzlehttp/promises/src/Promise.php:223
/var/www/html/vendor/guzzlehttp/promises/src/Promise.php:267
/var/www/html/vendor/guzzlehttp/promises/src/Promise.php:225
/var/www/html/vendor/guzzlehttp/promises/src/Promise.php:62
/var/www/html/vendor/guzzlehttp/guzzle/src/Client.php:131
/var/www/html/vendor/fabpot/goutte/Goutte/Client.php:180
/var/www/html/vendor/symfony/browser-kit/Client.php:318
/var/www/html/vendor/symfony/browser-kit/Client.php:259
/var/www/html/vendor/behat/mink-browserkit-
driver/src/BrowserKitDriver.php:696
/var/www/html/vendor/behat/mink-browserkit-
driver/src/BrowserKitDriver.php:480
/var/www/html/vendor/behat/mink/src/Element/NodeElement.php:153
/var/www/html/vendor/behat/mink/src/Element/NodeElement.php:161
/var/www/html/core/tests/Drupal/Tests/UiHelperTrait.php:100
/var/www/html/core/tests/Drupal/Tests/UiHelperTrait.php:209
/var/www/html/core/modules/config/tests/src/Functional/ConfigImportUpl
oadTest.php:50

ERRORS!
Tests: 1, Assertions: 9, Errors: 1.

```

### PR DESCRIPTION
**Pull request by alexpott**
Adds a test for and fixes #24

### CODE REVIEW

**Comment by mrook** [comment]
Thanks!

**Comment by alexpott** [comment]
@mrook thank you! Any idea of when a release will happen?

**Comment by mrook** [comment]
Just released 1.4.8!

**Comment by alexpott** [comment]
@mrook that's fantastic - thank you for speedy responses.

**Pull request merged**
