### PR TITLE
release of 1.4.0

### PR DESCRIPTION
**Pull request by cweiske**
@mrook - could you please release 1.4.0 so that pear-core 1.10.0 (which brings PHP7 support) can depend on it?

### CODE REVIEW

**Comment by LukasReschke** [comment]
Would be awesome to have this on packagist as well: https://packagist.org/packages/pear/archive_tar ;-)

**Comment by cweiske** [comment]
yep, the tag is missing

**Comment by cweiske** [comment]
@LukasReschke: I've tagged version 1.4.0

**Comment by mrook** [comment]
My bad, I forgot. Thanks @cweiske !

**Pull request merged**
