### PR TITLE
[Travis-CI] Add PHP 7 nightly and HHVM

### PR DESCRIPTION
**Pull request by Maks3w**

### CODE REVIEW

**Comment by mrook** [comment]
Thanks! Tests will need to be rewritten first to work on HHVM, as pear is not available on that env.

**Comment by Maks3w** [comment]
@mrook As you see HHVM is added as allow_failure. This means you are only tracking the progress but does not mean you expect to be compatible.

i.e. you can merge now and when test works remove it from `allow_failures`.

**Comment by mrook** [comment]
Yeah you're right ofcourse, it was more of a mental note :)

**Comment by Maks3w** [comment]
For my needs I only want PHP7 compatibility ASAP. We have some tests at ZF2 which fail due the use of to have the class name in a method too (PHP4 constructors)

**Pull request merged**
