### PR TITLE
WIP: more like an idea how to get this to run via composer

### PR DESCRIPTION
**Pull request by till**
@mrook Thoughts on this?

### CODE REVIEW

**Comment by cweiske** [comment]
we have pear-core-miminal now which provides PEAR.php and a couple of other files.

**Comment by mnapoli** [comment]
:+1:

**Comment by mrook** [comment]
:+1:

**Comment by mnapoli** [comment]
Could you please do a new release? I would like to use the library via composer in https://github.com/piwik/component-decompress (currently manually imported and committed in the repo)

**Comment by till** [comment]
@mnapoli you could try with dev-master and help us trial this?

**Comment by mrook** [comment]
@mnapoli @till let me know how that goes, I have no problems rolling a new release after.

**Comment by mrook** [comment]
I just pushed 1.3.14 which contains this change.

**Comment by till** [comment]
Awesome!

**Comment by mnapoli** [comment]
The 1.3.14 version wasn't pushed to Packagist: https://packagist.org/packages/pear/archive_tar Have you set up the github hook?

Furthermore, I can't use `dev-master` either because it doesn't seem to be registered in Packagist too.

**Comment by mrook** [comment]
Hm a few things have gone wrong. I'm apparently not the maintainer of the packagist package (should be fixed later today), and there is a parse error in composer.json. I'll push a 1.3.15 once that is fixed. Sorry!

**Comment by till** [comment]
@mrook maybe add `composer validate` to `.travis.yml`?

**Comment by mrook** [comment]
Yup, good point.

**Comment by mnapoli** [comment]
Gave it a try with `dev-master` and it works like a charm! @mrook I have to trouble you one more time though :p The 1.3.14 tag has the corrupted `composer.json` and so it doesn't appear on Packagist.

I think you have to tag a 1.3.15 :/

**Comment by mrook** [comment]
@mnapoli yeah I was afraid of that. No worries! I'll push 1.3.15 once the hook works.

**Comment by mrook** [comment]
Done!

**Pull request merged**
